---
title: 'Tytuł: zadanie_03'
author: 'Autor: Aleksandra Gomolka'
date: 'Data: `r Sys.Date()`'
output:
  html_document: default
  pdf_document: default
---

# Wykres 
Wykres o generacji zrodel wiatrowych i fotowoltaicznych dla danych za ostatnie 7 dni



```{r, echo=F, results="asis", fig.height=5, fig.width=10, fig.cap="Wykres dla zadania 3"}

    library(ggplot2)
    library(reshape2)

    dates <- lapply(gsub("-","",as.character(seq(from=Sys.Date()-6,to=Sys.Date(),by="1 day"))),function(d){d})
  
    download.file(url=paste("https://www.pse.pl/getcsv/-/export/csv/PL_GEN_WIATR/data/", dates[1][1], sep=""),
                destfile=paste(dates[1][1],".csv",sep=""), method="curl")
    d <- read.table(file=paste( dates[1][1], ".csv", sep=""), sep=";",dec=",",header=T,fileEncoding="CP1250")
    
    for(date in dates[c(2:length(dates))]){
      download.file(url=paste("https://www.pse.pl/getcsv/-/export/csv/PL_GEN_WIATR/data/",date[1],sep=""),
                    destfile=paste(date[1],".csv",sep=""), method="curl")
      
      d_temp <- read.table(file=paste(date[1], ".csv", sep=""), sep=";",dec=",",header=T,fileEncoding="CP1250")
      d <- rbind(d, setNames(d_temp, names(d_temp)))
    }
    
    d$Godzina <- as.integer(d$Godzina)
    d$Timestamp <- as.POSIXct(paste0(d$Data," ",d$Godzina-1,":00:00"),tz="GMT")
    
    d <- d[order(d$Timestamp),]
    
    #plot(x=d$Timestamp,y=d$Generacja.źródeł.wiatrowych,xlab="",ylab="",main="eee")
    #lines(x=d$Timestamp,y=d$Generacja.źródeł.fotowoltaicznych,col="red")
    
    d.long <- melt(d, id = "Timestamp", measure = c("Generacja.źródeł.fotowoltaicznych", "Generacja.źródeł.wiatrowych"))
    #ggplot(d.long, aes(Timestamp, value, colour = variable)) + geom_line()
    
    img <- ( 
      ggplot(d.long, aes(Timestamp, value, colour = variable))
      + 
        xlab("Czas") 
      +
        scale_y_continuous("Generacja.źródeł.fotowoltaicznych",
                           sec.axis = sec_axis(~ . * 30.48,name="Generacja.źródeł.wiatrowych"))
      # #~ . * 1.20; ~.*30.48
      +
        geom_line() 
      + 
        geom_point() 
      #+ 
       # geom_smooth()
    )
    print(img)
    

```
# Tabela 
Tabela z danymi. Tabela powinna miec kolumny: Timestamp;Wiatr;PV; Tabelka ma zawierac sie w osobnym rozdziale raportu.

```{r,echo=F,results="asis"}
    library(knitr)

    d <- d[c("Generacja.źródeł.wiatrowych", "Generacja.źródeł.fotowoltaicznych", "Timestamp")]
    colnames(d) <- c("Wiatr","PV","Timestamp")
    kable( d, caption="Oczekiwana tabela")
#print(head(d))
```